feature_list:
  - a_feature_column_name
  - another_feature_column_name

#table_name: "prepped_20210601"
target: "the_target_column_name"
models:
  #"xgboostclassifier"
  #"logisticregression"
  #linearmodel:
  #  linearmodel__normalize:
  #    - "False"
  #    - "True"
  #knn:
  #  k:
  #    - 3
  #    - 8
  #  range: "false"
  #randomforestregressor
  #randomforestclassifier:
  #   # max_depth:
  #   #   - 5
  #   #   - 10
  #  randomforestclassifier__n_estimators:
  #    - 100
  #catboostregressor
  xgboostregressor
  #  xgboostregressor__eta:
  #    - 0.01
  #  xgboostregressor__max_depth:
  #    - 15
  #  xgboostregressor__booster:
  #    - 'gbtree'
  #    #- 'gblinear'
  #  xgboostregressor__min_child_weight:
  #    - 6
  # svm
  # mlpclassifier:
  #   mlpclassifier__solver:
  #     - lbfgs
  #     - adam
  #   mlpclassifier__max_iter:
  #     - 1000