feature_list:
  - account_balance
  - country_France
  - country_Germany
  - country_Spain
  - has_life_insurance
  - has_health_insurance
  - number_of_products
  - 'sex_Female'
  - 'sex_Male'
  - 'tenure_0'
  - 'tenure_1'
  - 'tenure_10'
  - 'tenure_2'
  - 'tenure_3'
  - 'tenure_4'
  - 'tenure_5'
  - 'tenure_6'
  - 'tenure_7'
  - 'tenure_8'
  - 'tenure_9'
#table_name: "prepped_20210601"
target: churn
eval_type: categorical
models:
  "xgboostclassifier"
  #"logisticregression"
  #linearmodel:
  #  linearmodel__normalize:
  #    - "False"
  #    - "True"
  #knn:
  #  k:
  #    - 3
  #    - 8
  #  range: "false"
  #randomforestregressor
  #randomforestclassifier:
  #   # max_depth:
  #   #   - 5
  #   #   - 10
  #  randomforestclassifier__n_estimators:
  #    - 100
  #catboostregressor
  #xgboostregressor
  #  xgboostregressor__eta:
  #    - 0.01
  #  xgboostregressor__max_depth:
  #    - 15
  #  xgboostregressor__booster:
  #    - 'gbtree'
  #    #- 'gblinear'
  #  xgboostregressor__min_child_weight:
  #    - 6
  # svm
  # mlpclassifier:
  #   mlpclassifier__solver:
  #     - lbfgs
  #     - adam
  #   mlpclassifier__max_iter:
  #     - 1000